version: "3"

tasks:
  install:
    cmds:
      - go mod tidy
  upgrade:
    cmds:
      - go get -u ./...
  clean: # task tidy
    cmds:
      - go clean -modcache
  tidy: # task tidy
    cmds:
      - go mod tidy
